version: '3.2'

volumes:
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 0.0.0.0:9090:9090
        restart: always

    alertmanager-bot:
        command:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=debug
        - --store=bolt
        - --bolt.path=/data/bot.db
        ports:
            - 0.0.0.0:8080:8080
        environment:
          TELEGRAM_ADMIN: "408760550"
          TELEGRAM_TOKEN: 5164095874:AAFofGn4uDVdws9ZvK76lHH7xMVXnhCJfyQ
        image: metalmatze/alertmanager-bot:0.4.3
        restart: always
        volumes:
        - ./data:/data

    alertmanager:
        image: prom/alertmanager:v0.12.0
        ports:
          - 0.0.0.0:9093:9093
        volumes:
          - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'


    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 0.0.0.0:9100:9100
        restart: always

    blackbox-exporter:
      image: prom/blackbox-exporter
      ports:
        - 0.0.0.0:9115:9115
      restart: always
      volumes:
        - ./blackbox:/config
      command: --config.file=/config/blackbox.yml

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 0.0.0.0:3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        restart: always
